#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
cd "${REPO_ROOT}"
source "${REPO_ROOT}/setup_env.sh"

TABLE4_LABEL="${TABLE4_LABEL:?TABLE4_LABEL is required}"
TABLE4_INPUT="${TABLE4_INPUT:?TABLE4_INPUT is required}"
TABLE4_OUTPUT_DIR="${TABLE4_OUTPUT_DIR:?TABLE4_OUTPUT_DIR is required}"
TABLE4_DATASET_PATH="${TABLE4_DATASET_PATH:?TABLE4_DATASET_PATH is required}"
TABLE4_REFERENCE_SUBSETS_JSON="${TABLE4_REFERENCE_SUBSETS_JSON:?TABLE4_REFERENCE_SUBSETS_JSON is required}"
TABLE4_REFERENCE_SIZE="${TABLE4_REFERENCE_SIZE:-1000}"
TABLE4_REFERENCE_SUBSETS="${TABLE4_REFERENCE_SUBSETS:-5}"
TABLE4_REFERENCE_SEED="${TABLE4_REFERENCE_SEED:-20260701}"
TABLE4_MAUVE_SEED="${TABLE4_MAUVE_SEED:-1234}"
TABLE4_MAX_GENERATED="${TABLE4_MAX_GENERATED:-1000}"
TABLE4_TOKENIZER="${TABLE4_TOKENIZER:-gpt2}"
TABLE4_DEVICE_ID="${TABLE4_DEVICE_ID:-0}"

echo "TABLE4_LABEL: ${TABLE4_LABEL}"
echo "TABLE4_INPUT: ${TABLE4_INPUT}"
echo "TABLE4_OUTPUT_DIR: ${TABLE4_OUTPUT_DIR}"
echo "TABLE4_DATASET_PATH: ${TABLE4_DATASET_PATH}"
echo "TABLE4_REFERENCE_SUBSETS_JSON: ${TABLE4_REFERENCE_SUBSETS_JSON}"
echo "TABLE4_REFERENCE_SIZE: ${TABLE4_REFERENCE_SIZE} TABLE4_REFERENCE_SUBSETS: ${TABLE4_REFERENCE_SUBSETS}"
echo "TABLE4_REFERENCE_SEED: ${TABLE4_REFERENCE_SEED} TABLE4_MAUVE_SEED: ${TABLE4_MAUVE_SEED}"

python3 scripts/eval/robust_mauve_bootstrap.py   --input "${TABLE4_LABEL}=${TABLE4_INPUT}"   --output-dir "${TABLE4_OUTPUT_DIR}"   --dataset-path "${TABLE4_DATASET_PATH}"   --reference-subsets-json "${TABLE4_REFERENCE_SUBSETS_JSON}"   --reference-size "${TABLE4_REFERENCE_SIZE}"   --num-subsets "${TABLE4_REFERENCE_SUBSETS}"   --reference-seed "${TABLE4_REFERENCE_SEED}"   --mauve-seed "${TABLE4_MAUVE_SEED}"   --tokenizer "${TABLE4_TOKENIZER}"   --device-id "${TABLE4_DEVICE_ID}"   --max-generated "${TABLE4_MAX_GENERATED}"
