#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
cd "${REPO_ROOT}"

MODEL_PATH="${MODEL_PATH:-kuleshov-group/cnndm-mdlm}" \
NUM_VISIBLE_DEVICES="${NUM_VISIBLE_DEVICES:-1}" \
BLOCK_SIZE="${BLOCK_SIZE:-32}" \
MAX_WINDOW_SIZE="${MAX_WINDOW_SIZE:-32}" \
ALIGN_INPUTS_TO_BLOCKS="${ALIGN_INPUTS_TO_BLOCKS:-true}" \
KV_CACHING="${KV_CACHING:-true}" \
CNNDM_MIN_NEW_TOKENS="${CNNDM_MIN_NEW_TOKENS:-50}" \
CNNDM_MIN_NEW_TOKENS_SOURCE="${CNNDM_MIN_NEW_TOKENS_SOURCE:-fixed50}" \
CNNDM_EOS_TOKEN_ID="${CNNDM_EOS_TOKEN_ID:-151643}" \
LEN_PENALTY="${LEN_PENALTY:-1.1}" \
REGULATION_START="${REGULATION_START:-80}" \
REPETITION_PENALTY="${REPETITION_PENALTY:-1.2}" \
CONF_THRESHOLD="${CONF_THRESHOLD:-1e6}" \
MAX_LENGTH="${MAX_LENGTH:-768}" \
MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-180}" \
CKPT="${CKPT:-best}" \
USE_EMA="${USE_EMA:-true}" \
THROUGHPUT_RUN="${THROUGHPUT_RUN:-false}" \
THROUGHPUT_WARMUP="${THROUGHPUT_WARMUP:-50}" \
THROUGHPUT_MEASUREMENTS="${THROUGHPUT_MEASUREMENTS:-1000}" \
THROUGHPUT_GLOBAL_MEASUREMENTS="${THROUGHPUT_GLOBAL_MEASUREMENTS:-true}" \
COMPILE_BACKBONE="${COMPILE_BACKBONE:-false}" \
COMPILE_MODE="${COMPILE_MODE:-none}" \
COMPILE_DYNAMIC="${COMPILE_DYNAMIC:-false}" \
LOGITS_PROCESSOR_NAMES="${LOGITS_PROCESSOR_NAMES:-[repetition_penalty_logits_processor,exponential_decay_length_penalty]}" \
bash bash_scripts/run_seq2seq_eval_cnndm.sh
