name: dllm-dev
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - python=3.12.9
  - pip=25.0
  - nvidia/label/cuda-12.4.1::cuda-nvcc=12.4.131
  - pip:
      - -r requirements-lock.txt
      - -e .
