entropy_eos_stopping_criteria:
  _target_: src.custom_transformers.generation.EntropyEosStoppingCriteria
  tokenizer: ${tokenizer}
  entropy_threshold: 4.0
  block_size: 128
  var_length: true
  num_matches: 2
