defaults:
  - base@_here_
  - _self_

_target_: src.denoiser.diffusion.EsoLM
config:
  _target_: src.denoiser.diffusion.EsoLMConfig
  alpha_0: 0.0
  batch_split: 0.0
  diffusion_shuffle: false
  diffusion_attn_mode: "bidirectional"
  sequential_shuffle: false
  sequential_attn_mode: "causal"
  loss_type: "elbo"
  num_iw_orders: 0
