_target_: src.datasets.tokenize_on_demand.CNNDailyMailDataset
split: "train"
max_source_length: 512
max_target_length: 180
dataset_path: "abisee/cnn_dailymail"
padding: false
add_special_tokens: true
source_prompt_text: null
target_prompt_text: "Summary: "
truncate: true