_target_: src.noise_schedule.noise_schedules.StaggeredNoise
eps: 1e-3
block_size: ${block_size}
desired_block_size: ${block_size}
max_block_size: ${eval:${.desired_block_size}*2}
length: ${model.config.length}
