defaults:
  - diffusion_generation_config@_here_
  - _self_
_target_: src.denoiser.diffusion.SetDiffusionGenerationConfig
max_window_size: ${block_size}
cache_full_infill_context: false
use_first_hitting_order_in_decode: false
infill_repetition_penalty_include_right_context: false
setdlm_infill_cache_promotion_order: l2r
fused_block_cache: null
